apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeployment
  namespace: test-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javawebapplabel
  template:
    metadata:
      name: javapod
      labels:
        app: javawebapplabel
    spec:
      containers:
      - name: javawebcontainer
        image: docker10100/java-web-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9980
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  selector:
    app: javawebapplabel
  ports:
  - port: 80
    targetPort: 9980

